project:
  type: website

website:
  title: "PAC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Models
        menu:
          - text: Base Submission
            href: Models/basesubmission.qmd
          - text: Model 1 (Income)
            href: Models/model1.qmd
          - text: Model 2 (Numeric Values)
            href: Models/model2.qmd
          - text: Model 3 (Categorical Variables)
            href: Models/model3.qmd
          - text: Model 4 (See What Sticks)
            href: Models/model4.qmd
          - text: Model 5 (Money Movement)
            href: Models/model5.qmd
          - text: Model 6 (Feature Selection)
            href: Models/model6.qmd
          - text: Model 7 (Trees)
            href: Models/model7.qmd
          - text: Model 8 (Ensemble Bagging)
            href: Models/model8.qmd
          - text: Model 9 (Gradient Boost)
            href: Models/model9.qmd
          - text: Model 10 (Tree Tuning)
            href: Models/model10.qmd
          - text: Model 11 (Optimized Ensemble)
            href: Models/model11.qmd
          - text: Model 12 (SVR)
            href: Models/model12.qmd
      - href: Models/best.qmd
        text: Best Model

format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    toc: true



