project:
  type: website

website:
  title: "PAC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Models
        menu:
          - text: Model 1
            href: Models/model1.qmd
          - text: Model 2
            href: Models/model2.ipynb

format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    toc: true



