# Best Model (Optimized Ensemble)

An ensemble model was used in this case, as well as in a few previous models. On the [scikit learn website](https://scikit-learn.org/stable/modules/ensemble.html#histogram-based-gradient-boosting), I found HistGradientBoostingRegressor, an alternative to GradientBoostingRegressor that they claim is "orders of magnitude faster" when the number of samples is large. In this specific model, the learning_rate is reduced and max_iter is increased to refine the model's accuracy. In previous models I experimented with including only certain variables, and some of those models did see an improvement because of it. However, in this model I found that including all variables consistently led to better results.

I used the data itself to predict a rough RMSE, which in almost every model did end up aligning closely with the PAC scores. This helped with making minor adjustments to each model to hopefully be able to provide a submission that would perform well in the competition. This optimized ensemble model proved to be the best of my models both in the public and private scores.

```{python}
#| warning: false

import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor

data = pd.read_csv('../PACFiles/analysis_data.csv')
X = pd.get_dummies(data.drop(['customer_id', 'monthly_spend'], axis=1), drop_first=True)
y = data.monthly_spend

model = HistGradientBoostingRegressor(max_iter=500, learning_rate=0.03, random_state=617)
model.fit(X,y)

scoring_data = pd.read_csv('../PACFiles/scoring_data.csv')
scoring_X = pd.get_dummies(scoring_data.drop(['customer_id'], axis=1), drop_first=True)
scoring_X = scoring_X.reindex(columns=X.columns, fill_value=0)
pred = model.predict(scoring_X)

submission_file = pd.DataFrame({'customer_id': scoring_data.customer_id, 'monthly_spend': pred})
submission_file.to_csv('../PACFiles/submission_file_12.csv', index=False)

from sklearn.metrics import root_mean_squared_error
train_pred = model.predict(X)
rmse = root_mean_squared_error(y, train_pred)
print("Training RMSE:", rmse)
```